[package]
name = "amm"
type = "contract"
authors = [""]
compiler_version = ">=0.19.4"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.16.7", directory = "yarn-project/aztec-nr/aztec" }
# tokens_ordering = { path = "../tokens-ordering" }
address_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.16.7", directory = "yarn-project/aztec-nr/address-note" }
value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.16.7", directory = "yarn-project/aztec-nr/value-note" }
easy_private_state = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.16.7", directory = "yarn-project/aztec-nr/easy-private-state" }
safe_math = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.16.7", directory = "yarn-project/aztec-nr/safe-math" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.16.7", directory = "yarn-project/aztec-nr/authwit" }
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.16.7", directory = "yarn-project/noir-protocol-circuits/src/crates/types" }
