[package]
name = "tokens_ordering"
type = "lib"
authors = [""]
compiler_version = ">=0.19.4"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.16.7", directory = "yarn-project/aztec-nr/aztec" }
